---
title: "Rural Reading Rainbow"
authors:
  - admin
date: "2020-10-13"
slug: rural-reading-rainbow
summary: "Rural Reading Rainbow is an evidence-based project to reduce discrimination against LGBTQ+ students and increase the visibility of LGBTQ+ culture in Southern New Mexico."
categories:
  - Service
  - LGBTQ
  - Activism
tags:
- community
- service
- Las Cruces
- PFLAG
image:
  caption: "Photo courtesy of PFLAG.com"
  focal_point: ""
  preview_only: true
output: blogdown::html_page
---

<center>
[TL;DR]
</center>

Good news! I wrote a grant on behalf of PFLAG Las Cruces and we won $5,000 to fund a project a designed. Special thanks to the [Envision Fund](https://www.santafecf.org/envisionfund) of the Santa Fe Community Foundation!

Let me tell you about Rural Reading Rainbow.

# Summary of the Project
___
Aligned with the enhancement of cultural vibrancy in southern New Mexico, Rural Reading Rainbow is an evidence-based project to reduce discrimination against LGBTQ+ students and increase the visibility of LGBTQ+ culture by (1) providing LGBTQ-themed literature to schools and libraries, (2) implementing cultural enrichment events, and (3) partnering with culturally diverse LGBTQ+ students through funded internships.

The project targets the New Mexican counties of Doña Ana, Grant, Luna, Otero, and Sierra.

Given that one aim of Rural Reading Rainbow is the provision of LGBTQ-themed literature and children’s programming to schools and community libraries, our project is aligned with anti-bullying / safe school-based efforts for LGBTQ students. 

For example, research shows that accessible LGBTQ-themed literature increases student belongingness and enhances the cultural competency of non-LGBTQ community members (Brand & Maasch, 2017). 

Such an initiative may also increase the multicultural competence of teachers, staff, and other educational stakeholders regarding family diversity (e.g., Blackburn & Clark, 2011).

## Why is This Needed?

Compared to urban peers (sexual orientation [SO] = 3.85; gender identity [GI] = 2.87), LGBTQ+ youth in rural areas are more likely to experience victimization due to less supportive community climates (SO = 4.97; GI = 3.44, p < .001; Kosciw et al., 2015). Additionally, students in schools without LGBTQ-inclusive curricula are more likely to feel unsafe (Kosciw et al., 2018). Only 20% of students report positive representations of LGBTQ+ people (GLSEN, 2019). 

# Goals and Objectives
___
Our project has 3 overarching goals and 15 subordinate objectives.

1.	Provision of LGBTQ-inclusive curricular resources to schools and libraries in five high-poverty counties
    * Develop relationships with administrators, librarians, and teachers
    * Establish a list of libraries (from 16) and schools (from 136) willing to receive and display our book donations (i.e., Lambda Literary)
    * Establish a point of contact (PoC) at each institution
    * Connect the PoC with PFLAG and GLSEN resources (e.g., safe zone training).
    * Distribute LGBTQ-themed literature to PoCs
    * If schools or libraries are unwilling to receive donations, we will select different titles to distribute to existing partners

2.	Implementation of cultural enrichment events
    * Establish a Drag Queen Story Hour in southern New Mexico in collaboration with drag performers in Las Cruces, Deming, Silver City, and Alamogordo
    * Create promotion media for the events
    * Release announcements and stories through various channels
    * Leverage developed relationships (see 1.a) to promote a monthly Drag Queen Story Hour, either via Zoom or in-person

3.	Partnership with culturally diverse LGBTQ+ students
    * Create an internship application for students and distribute to NMSU programs
    * Select two student interns to assist with the project
    * Invite the interns to participate in board meetings to learn about non-profits
    * Train the interns in project management
    * Provide supervision and feedback to interns

# Rationale
___
In rural areas, few LGBTQ+ students are out to their peers (39.6%) and school staff (24.1%; Kosciw et al., 2015). 

Coming out, which is easier when environments are perceived as supportive, can result in lower levels of depression and greater overall well-being (Russell et al., 2011). 

Although coming out early can increase the risk of victimization (Kosciw et al., 2018), the outcome may be less likely if non-LGBTQ peers are exposed to LGBTQ-inclusive curricula. 

Indeed, Kappus (2016) found that LGBTQ+ parents, with children in PK-12 school systems within Doña Ana county, wanted their children’s classrooms to include LGBTQ literature. 

LGBTQ+ students in schools with LGBTQ-themed resources report fewer depressive symptoms, substance use, and suicidal thoughts (Goodenow et al., 2006; Hatzenbuehler et al., 2014; Poteat et al., 2013). 

Greater resources may also increase peer support which, in turn, is related to positive mental health, self-acceptance, and well-being (Shilo & Savaya, 2011).

# TL;DR
___
The Rural Reading Rainbow project:

* is funded $5,000 by the [Envision Fund](https://www.santafecf.org/envisionfund) of the Santa Fe Community Foundation
* provides LGBTQ-themed literature to schools and libraries
* implements cultural enrichment events
* partners with culturally diverse LGBTQ+ students through funded internships

### References
___
Blackburn, M. V., & Clark, C. T. (2011). Analyzing talk in a long-term literature discussion group: Ways of operating within LGBT-inclusive and queer discourses. *Reading Research Quarterly, 46*(3), 222–248.

Brand, S. T., & Maasch, S. L. (2017). Updating classroom libraries and cross-curricular activities: Celebrating gender identity and diversity through LGBTQ books. *Childhood Education, 93*(5), 430–439. https://doi.org/10.1080/00094056.2017.1367240

GLSEN. (2019). *2017 state snapshot: School climate in New Mexico*. https://www.glsen.org/sites/default/files/2019-11/New%20Mexico_Snapshot_2017_0.pdf

Goodenow, C., Szalacha, L., & Westheimer, K. (2006). School support groups, other school factors, and the safety of sexual minority adolescents. *Psychology in the Schools, 43*(5), 573–589. https://doi.org/10.1002/pits.20173

Hatzenbuehler, M. L., Birkett, M., Van Wagenen, A., & Meyer, I. H. (2014). Protective school climates and reduced risk for suicide ideation in sexual minority youths. *American Journal of Public Health, 104*(2), 279–286. https://doi.org/10.2105/AJPH.2013.301508

Kappus, B. (2016). *LGBTQ parents: Their perceptions and attitudes regarding their ontological experiences within their children’s school environment* (Publication No. 10141462) [Doctoral dissertation, New Mexico State University]. ProQuest Dissertations and Theses Global.

Kosciw, J. G., Greytak, E. A., Zongrone, A. D., Clark, C. M., & Truong, N. L. (2018). *The 2017 national school climate survey: The experiences of lesbian, gay, bisexual, transgender, and queer youth in our nation’s schools*. GLSEN.

Kosciw, J. G., Palmer, N. A., & Kull, R. M. (2015). Reflecting resiliency: Openness about sexual orientation and/or gender identity and its relationship to well-being and educational outcomes for LGBT students. *American Journal of Community Psychology, 55*(1–2), 167–178. https://doi.org/10.1007/s10464-014-9642-6

Poteat, V. P., Sinclair, K. O., DiGiovanni, C. D., Koenig, B. W., & Russell, S. T. (2013). Gay–straight alliances are associated with student health: A multischool comparison of LGBTQ and heterosexual youth. *Journal of Research on Adolescence, 23*(2), 319–330. https://doi.org/10.1111/j.1532-7795.2012.00832.x

Russell, S. T., Ryan, C., Toomey, R. B., Diaz, R. M., & Sanchez, J. (2011). Lesbian, gay, bisexual, and transgender adolescent school victimization: Implications for young adult health and adjustment. *Journal of School Health, 81*(5), 223–230. https://doi.org/10.1111/j.1746-1561.2011.00583.x

Shilo, G., & Savaya, R. (2011). Effects of family and friend support on LGB youths’ mental health and sexual orientation milestones. *Family Relations, 60*(3), 318–330. https://doi.org/10.1111/j.1741-3729.2011.00648.x