---
title: "Loving vs. Crushing"
authors:
  - admin
date: "2019-08-14"
slug: loving-vs-crushing
summary: "A brief meditation on the difference between loving and crushing, written from a monogamous point of view."
categories:
  - Creativity
tags:
- poem
- love
- passion
- reflections
image:
  caption: "Photo courtesy Marcelo Chagas"
  focal_point: ""
  preview_only: true
output: blogdown::html_page
---

Love is bad breath and bed hair.

Unglamorous chapped lips. Cold sores—cold feet on your calves—keeping score, but letting him win anyway.

Love is dumpster diving because he lost his ring, again. 

Baking your favorite bread when I have no idea how to cook, much less use yeast.

Love is messy. Pee on the toilet seat—sorry, I'll clean it.

Around you I hyena-heave and snort. Can't stand when you leave—can't take too much—can't stand you.

Can't take it back but still you come home. Never alone.

Crushing on you is cottonmouth—wet palms—bubbles in my gut I don't let out (except for one that I blush about and over think).

Do I stink? Do you like my hair? What do you think about traveling somewhere?

Crushing isn't fair—a dash—panting like a pug.

It’s reruns of you yawning, stretching, lounging in a lawn chair.

Unable to unplug. Unwilling to unglue my eyes from my iPhone, wishing you would text me first.

Thirst.

That's what crushing is.