---
title: "Open Stats Lab One-way ANOVA in R Using Data from Bastian, Jetten, & Ferris (2014)"
authors:
  - admin
date: "2018-11-12"
slug: osl-bastian-jetten-ferris-2014
summary: "A solution to Kevin P. McIntyre's Open Stats Lab activity on one-way ANOVA using a data set from Bastian, Jetten, and Ferris (2014)."
categories:
  - R
  - Tutorial
tags:
  - anova
  - t-test
  - open data
image:
  caption: ""
  focal_point: ""
output: blogdown::html_page
---



<div id="open-stats-lab" class="section level1">
<h1>Open Stats Lab</h1>
<hr />
<p>Kevin P. McIntyre developed this amazing resource for students of psychology. Check out <a href="https://sites.trinity.edu/osl/">Open Stats Lab</a> for a collection of all activities.</p>
<p>Each activity includes an article from <em>Psychological Science</em>, a data set, and an activity to complete in SPSS. However, if you are an open source fanatic, you could also complete the activity in <a href="https://jasp-stats.org/">JASP</a>. For tips on how to use JASP, check out <a href="https://osf.io/t56kg/">this resource</a> created by Buchanan, Hopke, and Donaldson (2018).</p>
<p>I prefer to get my hands deep into the data. Dr. McIntyre does not <em>yet</em> offer an R activity to accompany the work of <a href="https://journals.sagepub.com/stoken/default+domain/yFi5kZDGWMGBNQY62zIE/full">Bastian, Jetten, and Ferris (2014)</a>, so here is one possible solution written in R.</p>
</div>
<div id="analysis" class="section level1">
<h1>Analysis</h1>
<hr />
<p>I will perform assumption checks for each test prior to running it. We already know that the data meet all assumptions, otherwise the authors would have used a different analytic approach. However, checking the assumptions is helpful because:</p>
<ol style="list-style-type: decimal">
<li>reproducibility and accuracy can be verified; and</li>
<li>if you are a student, then you should form the habit of testing assumptions.</li>
</ol>
<p>This analysis will follow the data science workflow advocated by <a href="https://r4ds.had.co.nz/introduction.html">Garrett Grolemund and Hadley Wickham</a>. First, we will set-up our session and import the data. Then, we must clean the data. Next, we will transform, model, and visualize the data to understand it. Finally, we will communicate our findings.</p>
<p>Our task is to perform four analyses.</p>
<ol style="list-style-type: decimal">
<li><strong>Independent t-Test</strong> - did participants differ significantly in their experience of pain intensity and pain unpleasantness?</li>
<li><strong>Independent t-Test</strong> - did participants experience significant differences in affect?</li>
<li><strong>Independent t-Test</strong> - did participants in the pain condition find their activity more threatening and challenging?</li>
<li><strong>One-way ANOVA</strong> - does pain lead to differences in group bonding?</li>
</ol>
<div id="import" class="section level2">
<h2>Import</h2>
<hr />
<p>Let’s load the packages necessary for this analysis into our workspace.</p>
<pre class="r"><code>library(tidyverse)
library(psych)
library(car)</code></pre>
<p>We can import the data set using a relative path because our working directory is set.</p>
<pre class="r"><code>bastian &lt;- read_csv(&quot;https://cjcascalheira.com/data/osl-bastian-jetten-ferris-2014/Bastian%20Jetten%20and%20Ferris%202014%20Experiment%201.csv&quot;)</code></pre>
</div>
<div id="clean" class="section level2">
<h2>Clean</h2>
<hr />
<p>Let’s find the variables of interest. After reading the <a href="https://sites.trinity.edu/osl/data-sets-and-activities/one-way-anova-activities">paper and activity instructions</a>, we know that we are looking for the following variables:</p>
<ul>
<li>pain versus control condition;</li>
<li>pain intensity and pain unpleasantness;</li>
<li>positive and negative affect;</li>
<li>threatening and challenging; and</li>
<li>group bonding.</li>
</ul>
<pre class="r"><code># Find variables of interest
names(bastian)</code></pre>
<pre><code>##  [1] &quot;subid&quot;               &quot;CONDITION&quot;           &quot;groupnumber&quot;        
##  [4] &quot;groupsize&quot;           &quot;subnumber&quot;           &quot;subage&quot;             
##  [7] &quot;subgender&quot;           &quot;gendercoded&quot;         &quot;subbornaus&quot;         
## [10] &quot;subbornloc&quot;          &quot;subausyears&quot;         &quot;subefl&quot;             
## [13] &quot;pain1secs&quot;           &quot;pain2secs&quot;           &quot;feel_interested&quot;    
## [16] &quot;feel_distressed&quot;     &quot;feel_excited&quot;        &quot;feel_upset&quot;         
## [19] &quot;feel_strong&quot;         &quot;feel_guilty&quot;         &quot;feel_scared&quot;        
## [22] &quot;feel_hostile&quot;        &quot;feel_enthusiastic&quot;   &quot;feel_proud&quot;         
## [25] &quot;feel_irritable&quot;      &quot;feel_alert&quot;          &quot;feel_ashamed&quot;       
## [28] &quot;feel_inspired&quot;       &quot;feel_nervous&quot;        &quot;feel_determined&quot;    
## [31] &quot;feel_attentive&quot;      &quot;feel_jittery&quot;        &quot;feel_active&quot;        
## [34] &quot;feel_afraid&quot;         &quot;task_threatening&quot;    &quot;task_fearful&quot;       
## [37] &quot;task_enjoyable&quot;      &quot;task_worrying&quot;       &quot;task_hostile&quot;       
## [40] &quot;task_challenging&quot;    &quot;task_stimulating&quot;    &quot;task_exhilarating&quot;  
## [43] &quot;task_painful&quot;        &quot;task_depressing&quot;     &quot;task_pitiful&quot;       
## [46] &quot;task_informative&quot;    &quot;task_exciting&quot;       &quot;task_frightening&quot;   
## [49] &quot;task_terrifying&quot;     &quot;task_intolerable&quot;    &quot;group101&quot;           
## [52] &quot;group102&quot;            &quot;group103&quot;            &quot;group104&quot;           
## [55] &quot;group105&quot;            &quot;group106&quot;            &quot;group107&quot;           
## [58] &quot;task_intensity&quot;      &quot;task_unpleasantness&quot; &quot;Threat_MEAN&quot;        
## [61] &quot;Challenge_MEAN&quot;      &quot;Pos_PANAS&quot;           &quot;Neg_PANAS&quot;</code></pre>
<p>We learned from the article that PANAS is a measure of affect. Let’s clean up these data by assigning new variable names. I like to follow <code>this_convention</code> when naming objects in R. This prevents me from constantly referring to the <code>names()</code> of the data frame to check punctuation, capitalization, etc.</p>
<pre class="r"><code># Select &amp; rename variables of interest
bastian_clean &lt;- bastian %&gt;%
  select(
    condition = CONDITION,
    group101:task_unpleasantness,
    threat_mean = Threat_MEAN,
    challenge_mean = Challenge_MEAN,
    pos_affect = Pos_PANAS,
    neg_affect = Neg_PANAS
  )</code></pre>
<p>A one-way ANOVA is performed on a factor with two or more levels. Right now, the <code>condition</code> column is an <code>integer</code>.</p>
<pre class="r"><code># Change condition to factor with two levels
bastian_clean$condition &lt;- factor(bastian_clean$condition,
                                  labels = c(&quot;Control&quot;, &quot;Pain&quot;))

# Ensure factor assignment worked
class(bastian_clean$condition)</code></pre>
<pre><code>## [1] &quot;factor&quot;</code></pre>
<p>We will need to compute the group bonding variable. Let’s do that ahead of time.</p>
<pre class="r"><code># Create bonding variable
bonding_mean &lt;- bastian_clean %&gt;%
  select(group101:group107) %&gt;%
  rowMeans()

bastian_clean &lt;- bastian_clean %&gt;%
  mutate(bonding_mean = bonding_mean)

# Verify new variable
head(bastian_clean$bonding_mean)</code></pre>
<pre><code>## [1] 3.428571 4.857143 1.714286 1.714286 3.857143 3.142857</code></pre>
<p>Independent, unpaired samples t-tests are simpler to execute in R if we separate the groups into variables.</p>
<pre class="r"><code># Separate the conditions for t-tests
control &lt;- bastian_clean %&gt;%
  filter(condition == &quot;Control&quot;)

pain &lt;- bastian_clean %&gt;%
  filter(condition == &quot;Pain&quot;)</code></pre>
<p>Data are ready for analysis!</p>
</div>
<div id="understand" class="section level2">
<h2>Understand</h2>
<hr />
<p>An <a href="https://libguides.library.kent.edu/SPSS/IndependentTTest">unpaired samples t-test</a> shares assumptions with a <a href="https://libguides.library.kent.edu/SPSS/OneWayANOVA">univariate ANOVA</a>. Three of these assumptions derive from experimental design, while the remaining three can be tested after data collection.</p>
<p>Remember, all samples in psychology should be randomly selected from the population.</p>
<p><strong>Experimental Design Assumptions</strong></p>
<ol style="list-style-type: decimal">
<li><p>Dependent, response variable that is a continuous <code>numeric</code>.</p></li>
<li>Independent, explanatory variable that is a categorical <code>factor</code>.
<ul>
<li>Unpaired sampled t-test compares the means of two groups (i.e., two levels of a factor).</li>
<li>One-way ANOVA compares the means of two or more groups (i.e., multiple levels of a factor).</li>
</ul></li>
<li>Independence of observations.
<ul>
<li>Participants are assigned to one group with no overlap.</li>
</ul></li>
</ol>
<p>All of the experimental design assumptions have been met.</p>
<p><strong>Data Collection Assumptions</strong></p>
<ol start="4" style="list-style-type: decimal">
<li>No significant outliers.
<ul>
<li>Tested with boxplots and by comparing discrepancies between mean and median.</li>
<li>ANOVA is a robust test. If all levels of the factor are skewed in the same direction, then the results from our ANOVA are still reliable.</li>
</ul></li>
<li>The data are normally distributed.
<ul>
<li>Tested with a Shapiro-Wilk test.</li>
<li>Visualized with histograms and density curves.</li>
</ul></li>
<li>The data are homoscedastic.
<ul>
<li>Primarily tested with Levene’s test.</li>
<li>Occasionally tested with Bartlett’s test, which is more sensitive to violations of normality.</li>
</ul></li>
</ol>
<p>Remember, the hypotheses of an independent t-test are:</p>
<p><span class="math display">\[ H_0: \mu_1 = \mu_2 \\ H_1: \mu_1 \neq \mu_2 \]</span></p>
<p>The hypotheses of a one-way ANOVA are:</p>
<p><span class="math display">\[ H_0: \mu_1 = \mu_2 = \mu_3 = \dotso = \mu_k \\ H_1: \text{at least one different} \]</span></p>
<p><strong>Note</strong>: Even if you perform the test in question first (as I do below), make sure to check the assumptions.</p>
<div id="descriptive-statistics" class="section level3">
<h3>Descriptive Statistics</h3>
<p>Let’s summarize the data with pipes and a call to <code>psych::describe</code>.</p>
<p>Save the information as variables to use for graphing later.</p>
<pre class="r"><code># Descriptive statistics for control group
(control_desc &lt;- control %&gt;%
  select(-starts_with(&quot;group&quot;), -condition) %&gt;%
  describe() %&gt;%
  select(mean, sd, se))</code></pre>
<pre><code>##                     mean   sd   se
## task_intensity      1.67 0.92 0.18
## task_unpleasantness 1.74 1.20 0.23
## threat_mean         1.11 0.30 0.06
## challenge_mean      2.38 0.91 0.18
## pos_affect          2.80 0.83 0.16
## neg_affect          1.27 0.37 0.07
## bonding_mean        3.14 1.09 0.21</code></pre>
<pre class="r"><code># Descriptive statistics for pain group
(pain_desc &lt;- pain %&gt;%
  select(-starts_with(&quot;group&quot;), -condition) %&gt;%
  describe() %&gt;%
  select(mean, sd, se))</code></pre>
<pre><code>##                     mean   sd   se
## task_intensity      6.07 2.00 0.38
## task_unpleasantness 6.00 1.96 0.38
## threat_mean         1.36 0.58 0.11
## challenge_mean      2.67 0.87 0.17
## pos_affect          3.05 0.82 0.16
## neg_affect          1.34 0.45 0.09
## bonding_mean        3.71 1.01 0.19</code></pre>
</div>
<div id="independent-t-test-of-pain" class="section level3 tabset tabset-pills">
<h3>Independent t-Test of Pain</h3>
<pre class="r"><code># Independent t-test pain
t.test(pain$task_intensity, control$task_intensity,
       paired = FALSE, var.equal = TRUE)</code></pre>
<pre><code>## 
##  Two Sample t-test
## 
## data:  pain$task_intensity and control$task_intensity
## t = 10.409, df = 52, p-value = 2.554e-14
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  3.557773 5.257042
## sample estimates:
## mean of x mean of y 
##  6.074074  1.666667</code></pre>
<p>Participants in the pain group (<em>M</em> = 6.07, <em>SD</em> = 2.00) rated the intensity of their pain higher than those in the control group (<em>M</em> = 1.67, <em>SD</em> = 0.92), <em>t</em>(52) = 10.41, <em>p</em> &lt; .001.</p>
<pre class="r"><code># Independent t-test unpleasantness
t.test(pain$task_unpleasantness, control$task_unpleasantness,
       paired = FALSE, var.equal = TRUE)</code></pre>
<pre><code>## 
##  Two Sample t-test
## 
## data:  pain$task_unpleasantness and control$task_unpleasantness
## t = 9.6349, df = 52, p-value = 3.695e-13
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  3.372193 5.146325
## sample estimates:
## mean of x mean of y 
##  6.000000  1.740741</code></pre>
<p>Those subjected to the ice water task and squats (<em>M</em> = 6.00, <em>SD</em> = 1.96) were more likely than their counterparts (<em>M</em> = 1.74, <em>SD</em> = 1.20) to report an unpleasant experience, <em>t</em>(52) = 9.63, <em>p</em> &lt; .001.</p>
<div id="significant-outliers" class="section level4">
<h4>Significant outliers?</h4>
<p>Outliers skew distributions.</p>
<pre class="r"><code>bastian_clean %&gt;% 
  select(condition, task_intensity, task_unpleasantness) %&gt;%
  gather(task, pain, -condition) %&gt;%
  ggplot(aes(x = condition, y = pain)) +
    geom_boxplot() +
    facet_wrap(~ task)</code></pre>
<p><img src="/post/osl-bastian-jetten-ferris-2014_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p>Yes, there are outliers in the control group. Normality may be affected.</p>
</div>
<div id="normality" class="section level4">
<h4>Normality?</h4>
<p>The Shapiro-Wilk test enables us to examine if the data are normally distrbuted.</p>
<p><strong>Normality Check for Task Intensity</strong></p>
<pre class="r"><code>with(bastian_clean, shapiro.test(task_intensity[condition == &quot;Control&quot;]))</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  task_intensity[condition == &quot;Control&quot;]
## W = 0.72757, p-value = 9.608e-06</code></pre>
<p>Since <em>p</em> &lt; .001, we reject the null hypothesis that the distribution of task intensity is normal for the control group.</p>
<pre class="r"><code>with(bastian_clean, shapiro.test(task_intensity[condition == &quot;Pain&quot;]))</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  task_intensity[condition == &quot;Pain&quot;]
## W = 0.95731, p-value = 0.3205</code></pre>
<p>The observations of the variable task intensity are normally distrbuted for the pain group (<em>p</em> = .321).</p>
<p><strong>Normality Check for Task Unpleasantness</strong></p>
<pre class="r"><code>with(bastian_clean, shapiro.test(task_unpleasantness[condition == &quot;Control&quot;]))</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  task_unpleasantness[condition == &quot;Control&quot;]
## W = 0.67573, p-value = 1.814e-06</code></pre>
<p>Once again, <em>p</em> &lt; .001, so we accept the alternative hypothesis; this distribution is not normal.</p>
<pre class="r"><code>with(bastian_clean, shapiro.test(task_unpleasantness[condition == &quot;Pain&quot;]))</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  task_unpleasantness[condition == &quot;Pain&quot;]
## W = 0.94595, p-value = 0.1707</code></pre>
<p>However, for the pain group, the distrbution of task unpleasantness <em>is</em> normal (<em>p</em> &lt; .171).</p>
<p>We can visualize normality with histograms.</p>
<pre class="r"><code>bastian_clean %&gt;% 
  select(condition, task_intensity, task_unpleasantness) %&gt;%
  gather(task, pain, -condition) %&gt;%
  ggplot(aes(x = pain)) +
  geom_histogram(bins = 10) +
  facet_grid(~ task + condition)</code></pre>
<p><img src="/post/osl-bastian-jetten-ferris-2014_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<p>Participants in the control group (i.e., those <em>not</em> subjected to ice water and squats) reported little pain and unpleasantness, hence the concentration of scores near 0.</p>
</div>
<div id="homoscedasticity" class="section level4">
<h4>Homoscedasticity?</h4>
<p>Are the variances homogeneous?</p>
<pre class="r"><code>leveneTest(task_intensity ~ condition, data = bastian_clean)</code></pre>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = median)
##       Df F value   Pr(&gt;F)   
## group  1  9.1429 0.003872 **
##       52                    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Since <em>p</em> &lt; .05, we reject the null hypothesis. The variances of intensity scores between the two groups are heteroscedastic.</p>
<pre class="r"><code>leveneTest(task_unpleasantness ~ condition, data = bastian_clean)</code></pre>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = median)
##       Df F value  Pr(&gt;F)  
## group  1   4.943 0.03057 *
##       52                  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>In terms of task unpleasantness, the variances between both groups are not equal.</p>
<p>So, why do we run the independent t-test anyways? Well, the <a href="http://oak.ucc.nau.edu/rh232/courses/EPS525/Handouts/Understanding%20the%20Independent%20t%20Test.pdf">independent t-test is robust</a>, which means that violations of normality and homoscedasticity do not necessarily entail the use of a non-parametric test.</p>
<p>Here, the sample sizes are equal and just shy of the recommended threshold of <em>n</em> = 30. This is why we set <code>var.equal = TRUE</code> in the call to <code>t.test()</code>. Equal sample sizes of 27 make these violations negligible.</p>
</div>
</div>
<div id="independent-t-test-of-affect" class="section level3 tabset tabset-pills">
<h3>Independent t-Test of Affect</h3>
<pre class="r"><code># Independent t-test neg_affect
t.test(pain$neg_affect, control$neg_affect, 
       paired = FALSE, var.equal = TRUE)</code></pre>
<pre><code>## 
##  Two Sample t-test
## 
## data:  pain$neg_affect and control$neg_affect
## t = 0.59546, df = 52, p-value = 0.5541
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -0.1579932  0.2913265
## sample estimates:
## mean of x mean of y 
##  1.337037  1.270370</code></pre>
<pre class="r"><code># Independent t-test pos_affect
t.test(pain$pos_affect, control$pos_affect, 
       paired = FALSE, var.equal = TRUE)</code></pre>
<pre><code>## 
##  Two Sample t-test
## 
## data:  pain$pos_affect and control$pos_affect
## t = 1.0852, df = 52, p-value = 0.2828
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -0.2075481  0.6964370
## sample estimates:
## mean of x mean of y 
##  3.048148  2.803704</code></pre>
<p>Groups neither differed between negative affect (pain: <em>M</em> = 1.34, <em>SD</em> = 0.45; control: <em>M</em> = 1.27, <em>SD</em> = 0.37, <em>t</em>(52) = 0.6, <em>p</em> = .554), nor positive affect (pain: <em>M</em> = 3.05, <em>SD</em> = 0.82; control: <em>M</em> = 2.80, <em>SD</em> = 0.83, <em>t</em>(52) = 1.09, <em>p</em> = .283).</p>
<div id="significant-outliers-1" class="section level4">
<h4>Significant outliers?</h4>
<pre class="r"><code>bastian_clean %&gt;% 
  select(condition, pos_affect, neg_affect) %&gt;%
  gather(valence, rating, -condition) %&gt;%
  ggplot(aes(x = condition, y = rating)) +
  geom_boxplot() +
  facet_wrap(~ valence)</code></pre>
<p><img src="/post/osl-bastian-jetten-ferris-2014_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<p>Some outliers in both groups for negative affect.</p>
</div>
<div id="normality-1" class="section level4">
<h4>Normality?</h4>
<p><strong>Normality Check for Negative Affect</strong></p>
<pre class="r"><code>with(bastian_clean, shapiro.test(neg_affect[condition == &quot;Control&quot;]))</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  neg_affect[condition == &quot;Control&quot;]
## W = 0.76082, p-value = 3.082e-05</code></pre>
<pre class="r"><code>with(bastian_clean, shapiro.test(neg_affect[condition == &quot;Pain&quot;]))</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  neg_affect[condition == &quot;Pain&quot;]
## W = 0.75295, p-value = 2.321e-05</code></pre>
<p>The scores of negative affect violate the assumption of normality (<em>p</em>s &lt; .001).</p>
<p><strong>Normality Check for Positive Affect</strong></p>
<pre class="r"><code>with(bastian_clean, shapiro.test(pos_affect[condition == &quot;Control&quot;]))</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  pos_affect[condition == &quot;Control&quot;]
## W = 0.97642, p-value = 0.7742</code></pre>
<pre class="r"><code>with(bastian_clean, shapiro.test(pos_affect[condition == &quot;Pain&quot;]))</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  pos_affect[condition == &quot;Pain&quot;]
## W = 0.95535, p-value = 0.2881</code></pre>
<p>However, for both the control (<em>p</em> = .774) and pain (<em>p</em> = .288) groups, reported values of positive affect are normally distributed.</p>
<pre class="r"><code># Visualize normality
bastian_clean %&gt;% 
  select(condition, pos_affect, neg_affect) %&gt;%
  gather(valence, rating, -condition) %&gt;%
  ggplot(aes(x = rating)) +
  geom_histogram(bins = 10) +
  facet_wrap(~ valence + condition)</code></pre>
<p><img src="/post/osl-bastian-jetten-ferris-2014_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
<p>Between-group distributions for affect look similar.</p>
</div>
<div id="homoscedasticity-1" class="section level4">
<h4>Homoscedasticity?</h4>
<pre class="r"><code>leveneTest(neg_affect ~ condition, data = bastian_clean)</code></pre>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = median)
##       Df F value Pr(&gt;F)
## group  1  0.1976 0.6585
##       52</code></pre>
<pre class="r"><code>leveneTest(pos_affect ~ condition, data = bastian_clean)</code></pre>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = median)
##       Df F value Pr(&gt;F)
## group  1  0.0727 0.7885
##       52</code></pre>
<p>Levene’s test revealed that the variances for both groups were homogeneous on measures of negative (<em>p</em> = .659) and positive (<em>p</em> = .789) affect.</p>
</div>
</div>
<div id="independent-t-test-of-challenge" class="section level3 tabset tabset-pills">
<h3>Independent t-Test of Challenge</h3>
<pre class="r"><code># Independent t.test challenge_mean
t.test(pain$challenge_mean, control$challenge_mean,
       paired = FALSE, var.equal = TRUE)</code></pre>
<pre><code>## 
##  Two Sample t-test
## 
## data:  pain$challenge_mean and control$challenge_mean
## t = 1.2227, df = 52, p-value = 0.227
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -0.1899875  0.7825800
## sample estimates:
## mean of x mean of y 
##  2.672840  2.376543</code></pre>
<pre class="r"><code># Independent t.test threat_mean
t.test(pain$threat_mean, control$threat_mean,
       paired = FALSE, var.equal = TRUE)</code></pre>
<pre><code>## 
##  Two Sample t-test
## 
## data:  pain$threat_mean and control$threat_mean
## t = 1.969, df = 52, p-value = 0.05429
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -0.004720298  0.498547458
## sample estimates:
## mean of x mean of y 
##  1.358025  1.111111</code></pre>
<p>The pain group perceived their tasks to be slightly more threatening (<em>M</em> = 1.36, <em>SD</em> = 0.58) than the control group (<em>M</em> = 1.11, <em>SD</em> = 0.30), <em>t</em>(52) = 1.97, <em>p</em> = .054, but not more challenging (pain: <em>M</em> = 2.67, <em>SD</em> = 0.87; control: <em>M</em> = 2.38, <em>SD</em> = 0.91, <em>t</em>(52) = 1.22, <em>p</em> = .227).</p>
<div id="significant-outliers-2" class="section level4">
<h4>Significant outliers?</h4>
<pre class="r"><code>bastian_clean %&gt;% 
  select(condition, threat_mean, challenge_mean) %&gt;%
  gather(task, rating, -condition) %&gt;%
  ggplot(aes(x = condition, y = rating)) +
  geom_boxplot() +
  facet_wrap(~ task)</code></pre>
<p><img src="/post/osl-bastian-jetten-ferris-2014_files/figure-html/unnamed-chunk-27-1.png" width="672" /></p>
<p>Outliers are present in both measures.</p>
</div>
<div id="normality-2" class="section level4">
<h4>Normality?</h4>
<p><strong>Normality Check for Challenge</strong></p>
<pre class="r"><code>with(bastian_clean, shapiro.test(challenge_mean[condition == &quot;Control&quot;]))</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  challenge_mean[condition == &quot;Control&quot;]
## W = 0.93271, p-value = 0.08057</code></pre>
<pre class="r"><code>with(bastian_clean, shapiro.test(challenge_mean[condition == &quot;Pain&quot;]))</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  challenge_mean[condition == &quot;Pain&quot;]
## W = 0.94361, p-value = 0.1496</code></pre>
<p>The distributions of perceived challenge for both conditions are normal.</p>
<p><strong>Normality Check for Threat</strong></p>
<pre class="r"><code>with(bastian_clean, shapiro.test(threat_mean[condition == &quot;Control&quot;]))</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  threat_mean[condition == &quot;Control&quot;]
## W = 0.4091, p-value = 2.255e-09</code></pre>
<pre class="r"><code>with(bastian_clean, shapiro.test(threat_mean[condition == &quot;Pain&quot;]))</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  threat_mean[condition == &quot;Pain&quot;]
## W = 0.67818, p-value = 1.955e-06</code></pre>
<p>The distribution of perceived threat is neither normal for the control group, nor pain group.</p>
<pre class="r"><code>bastian_clean %&gt;% 
  select(condition, threat_mean, challenge_mean) %&gt;%
  gather(task, rating, -condition) %&gt;%
  ggplot(aes(x = rating)) +
  geom_histogram(bins = 10) +
  facet_wrap(~ task + condition)</code></pre>
<p><img src="/post/osl-bastian-jetten-ferris-2014_files/figure-html/unnamed-chunk-30-1.png" width="672" /></p>
</div>
<div id="homoscedasticity-2" class="section level4">
<h4>Homoscedasticity?</h4>
<pre class="r"><code>leveneTest(challenge_mean ~ condition, data = bastian_clean)</code></pre>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = median)
##       Df F value Pr(&gt;F)
## group  1  0.0138 0.9068
##       52</code></pre>
<pre class="r"><code>leveneTest(threat_mean ~ condition, data = bastian_clean)</code></pre>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = median)
##       Df F value  Pr(&gt;F)  
## group  1   3.877 0.05429 .
##       52                  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Data for each measure are homoscedastic (both <em>p</em>s &gt; 0.05).</p>
</div>
</div>
<div id="one-way-anova" class="section level3 tabset tabset-pills">
<h3>One-way ANOVA</h3>
<pre class="r"><code># Model the variance
bastian_aov &lt;- aov(bonding_mean ~ condition, data = bastian_clean)

# Summarize the ANOVA
anova(bastian_aov)</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Response: bonding_mean
##           Df Sum Sq Mean Sq F value  Pr(&gt;F)  
## condition  1  4.490  4.4902  4.0876 0.04836 *
## Residuals 52 57.122  1.0985                  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Since <em>p</em> = .048 is less than our significance value of $= 0.05 $, the <em>F</em> value exceeds the critical value. We reject the null hypothesis.</p>
<p>Enduring pain with others has a mild effect on social bonding. Participants who perform the pain tasks with others reported a greater sense of being connected (<em>M</em> = 3.71, <em>SD</em> = 1.01) than those who perform non-painful tasks (<em>M</em> = 3.14, <em>SD</em> = 1.09), <em>F</em>(1, 52) = 4.09, <em>p</em> = .048.</p>
<div id="significant-outliers-3" class="section level4">
<h4>Significant outliers?</h4>
<pre class="r"><code>ggplot(bastian_clean, aes(x = condition, y = bonding_mean)) +
  geom_boxplot()</code></pre>
<p><img src="/post/osl-bastian-jetten-ferris-2014_files/figure-html/unnamed-chunk-33-1.png" width="672" /></p>
<p>It appears only two participants felt relatively disconnected after sharing pain with strangers.</p>
</div>
<div id="normality-3" class="section level4">
<h4>Normality?</h4>
<pre class="r"><code>with(bastian_clean, shapiro.test(bonding_mean[condition == &quot;Control&quot;]))</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  bonding_mean[condition == &quot;Control&quot;]
## W = 0.9563, p-value = 0.3035</code></pre>
<pre class="r"><code>with(bastian_clean, shapiro.test(bonding_mean[condition == &quot;Pain&quot;]))</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  bonding_mean[condition == &quot;Pain&quot;]
## W = 0.85828, p-value = 0.001688</code></pre>
<p>Data from the control condition (<em>p</em> = .304) are normally distributed, but are non-normal for the pain group (<em>p</em> = .002).</p>
<p>It is possible, and advisable, to check for normality among the residuals of an <code>aov</code> object.</p>
<pre class="r"><code>bastian_residuals &lt;- residuals(object = bastian_aov)
shapiro.test(bastian_residuals)</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  bastian_residuals
## W = 0.93396, p-value = 0.005261</code></pre>
<p>The residuals are not normally distributed. However, like the independent t-test, a one-way ANOVA is <em>robust</em>. One condition is normal, while the other is not. The violation of normality is moderate.</p>
<pre class="r"><code>ggplot(bastian_clean, aes(x = bonding_mean)) +
  geom_histogram(bins = 10) +
  facet_wrap(~ condition)</code></pre>
<p><img src="/post/osl-bastian-jetten-ferris-2014_files/figure-html/unnamed-chunk-36-1.png" width="672" /></p>
<p>Most participants in the pain group rated their sense of bonding above 3.</p>
</div>
<div id="homoscedasticity-3" class="section level4">
<h4>Homoscedasticity?</h4>
<pre class="r"><code>leveneTest(bonding_mean ~ condition, data = bastian_clean)</code></pre>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = median)
##       Df F value Pr(&gt;F)
## group  1  0.2897 0.5927
##       52</code></pre>
<p>The <em>F</em> value does not exceed the critical value, so we accept the null hypothesis. The data are homoscedastic, <em>F</em>(1, 59) = 0.29, <em>p</em> = .593.</p>
</div>
</div>
<div id="visualize" class="section level3">
<h3>Visualize</h3>
<p>Now we can create a bar graph depicting the degree of error.</p>
<p>First, construct a <code>ggplot2</code> theme consistent with APA-style.</p>
<pre class="r"><code>apa_theme &lt;- theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        axis.line = element_line(),
        plot.title = element_text(hjust = 0.5),
        text = element_text(size = 12))</code></pre>
<p>Remember those R objects holding our descriptive statistics?</p>
<p>Only the summary statistics for <code>bonding_mean</code> are necessary. After selecting those, we will assign the condition as a new variable.</p>
<pre class="r"><code>control_dynamite &lt;- control_desc %&gt;%
  mutate(measure = row.names(control_desc)) %&gt;%
  select(measure, mean, se) %&gt;%
  filter(measure == &quot;bonding_mean&quot;) %&gt;%
  mutate(condition = &quot;Control&quot;)

pain_dynamite &lt;- pain_desc %&gt;%
    mutate(measure = row.names(pain_desc)) %&gt;%
    select(measure, mean, se) %&gt;%
    filter(measure == &quot;bonding_mean&quot;) %&gt;%
    mutate(condition = &quot;Pain&quot;)</code></pre>
<p>Finally, we will merge the data frames. The creation of a single data frame with the mean and standard error for both conditions makes plotting simple.</p>
<pre class="r"><code>(dynamite_plot &lt;- merge(pain_dynamite, control_dynamite,
                       by = c(&quot;measure&quot;, &quot;condition&quot;, &quot;mean&quot;, &quot;se&quot;), all = TRUE))</code></pre>
<pre><code>##        measure condition     mean        se
## 1 bonding_mean   Control 3.137566 0.2093075
## 2 bonding_mean      Pain 3.714286 0.1938049</code></pre>
<p>This code creates the bar graph.</p>
<pre class="r"><code>ggplot(dynamite_plot, aes(x = condition, y = mean, fill = condition)) +
  geom_bar(position = &quot;dodge&quot;, stat = &quot;identity&quot;, color = &quot;black&quot;, size = 0.5) +
  geom_errorbar(aes(ymin = mean-se, ymax = mean+se),
                width = 0.1, position = position_dodge(0.9)) +
  scale_fill_manual(values = c(&quot;Control&quot; = &quot;#FFFFFF&quot;, &quot;Pain&quot; = &quot;#999999&quot;),
                    labels = c(&quot;Control&quot;, &quot;Pain&quot;)) +
  labs(x = &quot;&quot;, y = &quot;Mean Level of Social Bonding&quot;) +
  
  expand_limits(y = c(1, 5)) +
  scale_y_continuous(breaks = 0:5) +
  apa_theme +
  theme(legend.position = &quot;none&quot;)</code></pre>
<p><img src="/post/osl-bastian-jetten-ferris-2014_files/figure-html/unnamed-chunk-41-1.png" width="672" /></p>
<p><strong>Figure 1.</strong> Results from Experiment 1 showing the mean level of social bonding reported for each group.</p>
</div>
</div>
<div id="communicate" class="section level2">
<h2>Communicate</h2>
<hr />
<p>Participants in the pain group (<em>M</em> = 6.07, <em>SD</em> = 2.00) rated the intensity of their pain higher than those in the control group (<em>M</em> = 1.67, <em>SD</em> = 0.92), <em>t</em>(52) = 10.41, <em>p</em> &lt; .001. Those subjected to the ice water task and squats (<em>M</em> = 6.00, <em>SD</em> = 1.96) were more likely than their counterparts (<em>M</em> = 1.74, <em>SD</em> = 1.20) to report an unpleasant experience, <em>t</em>(52) = 9.63, <em>p</em> &lt; .001. Groups neither differed between negative affect (pain: <em>M</em> = 1.34, <em>SD</em> = 0.45; control: <em>M</em> = 1.27, <em>SD</em> = 0.37, <em>t</em>(52) = 0.6, <em>p</em> = .554), nor positive affect (pain: <em>M</em> = 3.05, <em>SD</em> = 0.82; control: <em>M</em> = 2.80, <em>SD</em> = 0.83, <em>t</em>(52) = 1.09, <em>p</em> = .283). The pain group perceived their tasks to be slightly more threatening (<em>M</em> = 1.36, <em>SD</em> = 0.58) than the control group (<em>M</em> = 1.11, <em>SD</em> = 0.30), <em>t</em>(52) = 1.97, <em>p</em> = .054, but not more challenging (pain: <em>M</em> = 2.67, <em>SD</em> = 0.87; control: <em>M</em> = 2.38, <em>SD</em> = 0.91, <em>t</em>(52) = 1.22, <em>p</em> = .227).</p>
<p>Enduring pain with others has a mild effect on social bonding. Participants who perform the pain tasks with others reported a greater sense of being connected (<em>M</em> = 3.71, <em>SD</em> = 1.01) than those who perform non-painful tasks (<em>M</em> = 3.14, <em>SD</em> = 1.09), <em>F</em>(1, 52) = 4.09, <em>p</em> = .048.</p>
</div>
</div>
<div id="acknowledgements" class="section level1">
<h1>Acknowledgements</h1>
<hr />
<p>I am thankful for my advisor, Dr. Brandt A. Smith for introducing me to R, JASP, and OSL. The discipline of psychology is advocating for preregistered, open materials. His encouragement to utilize open data and open source software has positioned me in the middle of the reproducible movement.</p>
<p>I would still be clicking checkboxes and dropdowns to analyze data if it were not for <a href="https://www.datacamp.com">DataCamp</a>, <a href="https://rstudio-pubs-static.s3.amazonaws.com/65059_586f394d8eb84f84b1baaf56ffb6b47f.html">Rose Maier</a>, and <a href="http://www.sthda.com/english/wiki/r-software">Alboukadel Kassambara</a>.</p>
</div>
