---
title: "Open Stats Lab Factorial ANOVA in R Using Data from Maglio & Polman (2014)"
authors:
  - admin
date: "2018-11-26"
slug: osl-maglio-polman-2014
summary: "A solution to Kevin P. McIntyre's Open Stats Lab activity on factorial ANOVA using a data set from Maglio and Polman (2014)."
categories:
  - R
  - Tutorial
tags:
  - anova
  - factorial
  - t-test
  - open data
image:
  caption: ""
  focal_point: ""
output:
  blogdown::html_page:
    toc: true
    toc_depth: 2
---


<div id="TOC">
<ul>
<li><a href="#open-stats-lab">Open Stats Lab</a></li>
<li><a href="#analysis">Analysis</a><ul>
<li><a href="#import">Import</a></li>
<li><a href="#clean">Clean</a></li>
<li><a href="#understand">Understand</a></li>
<li><a href="#communicate">Communicate</a></li>
</ul></li>
<li><a href="#acknowledgements">Acknowledgements</a></li>
</ul>
</div>

<div id="open-stats-lab" class="section level1">
<h1>Open Stats Lab</h1>
<hr />
<p>Kevin P. McIntyre developed this amazing resource for students of psychology. Check out <a href="https://sites.trinity.edu/osl/">Open Stats Lab</a> for a collection of all activities.</p>
<p>Each activity includes an article from <em>Psychological Science</em>, a data set, and an activity to complete in SPSS. However, if you are an open source fanatic, you could also complete the activity in <a href="https://jasp-stats.org/">JASP</a>. For tips on how to use JASP, check out <a href="https://osf.io/t56kg/">this resource</a> created by Buchanan, Hopke, and Donaldson (2018).</p>
<p>I prefer to get my hands deep into the data. Dr. McIntyre does not <em>yet</em> offer an R activity to accompany the work of <a href="https://journals.sagepub.com/doi/pdf/10.1177/0956797614530571">Maglio and Polman (2014)</a>, so here is one possible solution written in R.</p>
</div>
<div id="analysis" class="section level1">
<h1>Analysis</h1>
<hr />
<p>I will perform assumption checks for each test prior to running it. We already know that the data meet all assumptions, otherwise the authors would have used a different analytic approach. However, checking the assumptions is helpful because:</p>
<ol style="list-style-type: decimal">
<li>reproducibility and accuracy can be verified; and</li>
<li>if you are a student, then you should form the habit of testing assumptions.</li>
</ol>
<p>This analysis will follow the data science workflow advocated by <a href="https://r4ds.had.co.nz/introduction.html">Garrett Grolemund and Hadley Wickham</a>. First, we will set-up our session and import the data. Then, we must clean the data. Next, we will transform, model, and visualize the data to understand it. Finally, we will communicate our findings.</p>
<div id="import" class="section level2">
<h2>Import</h2>
<hr />
<p>Setting up the workspace involves loading packages and importing the data.</p>
<pre class="r"><code>library(tidyverse)
library(car)
library(broom)
library(psych)</code></pre>
<p>A relative path is used because the working directory is set.</p>
<pre class="r"><code>maglio &lt;- read_csv(&quot;https://www.cjcascalheira.com/data/osl-maglio-polman-2014/Maglio%20and%20Polman%202014%20Experiment%201.csv&quot;)</code></pre>
</div>
<div id="clean" class="section level2">
<h2>Clean</h2>
<hr />
<p>Coding clarity is important since we did not design the study. Which integer of the <code>station</code> variable correponds to Spadina, St. George, Bloor-Yonge, and Sherbourne? It is reasonable to think that the assignment of integers reads from left to right based on the Green Line map (see activity description).</p>
<p>Calculation of the means enables verification of this assumption. Count is included to understand the grouping of participants better. We can compare our average subjective distance to the numbers reported in <a href="https://journals.sagepub.com/doi/pdf/10.1177/0956797614530571">Figure 1</a>.</p>
<pre class="r"><code>maglio %&gt;%
  group_by(direction, station) %&gt;%
  summarize(mean = mean(subjective_distance), count = n())</code></pre>
<pre><code>## # A tibble: 8 x 4
## # Groups:   direction [2]
##   direction station  mean count
##   &lt;chr&gt;       &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt;
## 1 EAST            1  3.65    26
## 2 EAST            2  2.77    26
## 3 EAST            3  1.61    23
## 4 EAST            4  2.77    26
## 5 WEST            1  2.64    25
## 6 WEST            2  1.64    25
## 7 WEST            3  2.19    26
## 8 WEST            4  4       25</code></pre>
<p>The assumption held true: 1 corresponds to Spadina, 2 to St. George, and so on.</p>
<p>Notice that the sample sizes in each <strong>cell</strong> are unequal. That is, the number of participants within each level combination of factors (i.e., Spadina East, Spadina West, etc.) varies. Four cells have 26 participants, three cells have 25 participants, and 1 cell has 23 participants.</p>
<p>Uneven sample sizes across cells creates an <strong>unbalanced design</strong>. This will affect the code we write to analyze these data.</p>
<p>But let’s not get ahead of ourselves. First, we must code these integers to transform <code>station</code> into a factor. Might as well transform <code>direction</code> and <code>orientation</code> into factors in the same call. The purpose of these transformations is to meet a requriement of factorial ANOVA: categorical predictors that are factors with two or more levels.</p>
<pre class="r"><code>maglio_clean &lt;- within(maglio, {
  station &lt;- factor(station, labels = c(&quot;spadina&quot;, &quot;st_george&quot;, &quot;bloor_yonge&quot;, &quot;sherbourne&quot;))
  direction &lt;- factor(direction)
  orientation &lt;- factor(orientation, labels = c(&quot;towards&quot;, &quot;away&quot;))
})</code></pre>
<p>We know from the instructions that our task includes conducting independent t-tests. Let’s split the data frame according the station and direction ahead of time.</p>
<pre class="r"><code>stations &lt;- c(&quot;spadina&quot;, &quot;st_george&quot;, &quot;bloor_yonge&quot;, &quot;sherbourne&quot;)

for (i in stations) {
  assign(paste(i, &quot;east&quot;, sep = &quot;_&quot;), 
         maglio_clean %&gt;% filter(station == i &amp; direction == &quot;EAST&quot;))
  assign(paste(i, &quot;west&quot;, sep = &quot;_&quot;), 
         maglio_clean %&gt;% filter(station == i &amp; direction == &quot;WEST&quot;))
}</code></pre>
</div>
<div id="understand" class="section level2">
<h2>Understand</h2>
<hr />
<p>A factorial ANOVA compares the means across two or more independent variables, thereby splitting the sample into four or more groups. Contrast this with a one-way ANOVA, which only has one independent variable that splits the sample into two or more groups. In terms of analyzing variance, if we have more than one independent variable, then conduct a factorial ANOVA. Notice that, in both cases, we only have <em>one</em> dependent variable.</p>
<p>The presence of two independent variables classifies a factorial ANOVA as two-way. The assumptions of a two-way ANOVA echo those of the one-way ANOVA. Three are met before data collection, three are tested.</p>
<p><strong>Assumptions Before Data Collection</strong></p>
<ol style="list-style-type: decimal">
<li><p><strong>Two or more categorical independent variables</strong> as factors with two or more levels;</p></li>
<li><p><strong>One continuous dependent variable</strong> at the interval or ratio level;</p></li>
<li><p><strong>Independence of observations</strong>, or a between-groups design, in which participants are separated into distinct groups with no overlap;</p></li>
</ol>
<p><strong>Tested Assumptions</strong></p>
<ol start="4" style="list-style-type: decimal">
<li><p><strong>No significant outliers</strong>, assessed with boxplots;</p></li>
<li><p><strong>Normality</strong>, assessed with the Shapiro-Wilk test, histograms, Q-Q plots, and density curves for each level combination of the two factors;</p></li>
<li><p><strong>Homoscedasticity</strong>, assessed with Levene’s test for each combination of the two factors.</p></li>
</ol>
<p>An analysis of variance is robust. It can provide valid results with minor violations of normality. Since the first three assumptions are met during experimental design, we must test for outliers, normality, and homogeneity of variances.</p>
<p>The null and alternative hypotheses, assessed with the <em>F</em> test, can make claims about the means between cells or claims about the interaction between factors. For this study, they are:</p>
<p><span class="math display">\[H_0: \text{there is no interaction between orientation and station} \\ H_1: \text{there is an interaction}\]</span></p>
<p>Maglio and Polman (2014) conducted a 2 x 4 between-groups factorial experiment. The first factor, <code>direction</code>, has two levels: eastbound and westbound. The second factor, <code>station</code>, has four levels: Spadina, St. George, Bloor-Yonge, and Sherbourne. Thus, the sample of participants is divided into eight groups.</p>
<div id="two-way-anova" class="section level3 tabset tabset-pills">
<h3>Two-way ANOVA</h3>
<p>Since we have an unbalanced design with unequal sample sizes in each cell, we must specify the type of <em>sum of squares</em>. Type-III is usually <a href="http://www.sthda.com/english/wiki/two-way-anova-test-in-r">recommended</a>. When the design in unbalanced, each type of <em>sum of squares</em> will yield different results.</p>
<p>With that in mind, let’s start by constructing the analysis of variance.</p>
<pre class="r"><code>maglio_aov &lt;- aov(subjective_distance ~ orientation * station, data = maglio_clean)</code></pre>
<p>Now we summarize the model to test for interaction effects. Note that we <em>must</em> include the <code>options()</code> call <strong>first</strong> since the sum of squares is Type III. Failure to do so will produce a correct effect with the interaction, but spurious effects for each factor by itself. In this case, failure to set <code>options()</code> will cause all effects to appear significant.</p>
<pre class="r"><code>options(contrasts = c(&quot;contr.sum&quot;, &quot;contr.poly&quot;))
(maglio_anova &lt;- Anova(maglio_aov, type = &quot;III&quot;))</code></pre>
<pre><code>## Anova Table (Type III tests)
## 
## Response: subjective_distance
##                     Sum Sq  Df F value    Pr(&gt;F)    
## (Intercept)         347.12   1 323.515 &lt; 2.2e-16 ***
## orientation          13.10   1  12.210 0.0005889 ***
## station              51.19   3  15.903 2.763e-09 ***
## orientation:station  52.41   3  16.283 1.765e-09 ***
## Residuals           208.15 194                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>There are two significant effects, one on station and the other on the interaction between orientation and station. Therefore, we should assess the effect size, or partial eta-squared. This is given by the equation:</p>
<p><span class="math display">\[\eta_p^2 = \frac{SS_{predictor}}{SS_{predictor} + SS_{residuals}}\]</span></p>
<p>We can use <code>broom::tidy</code> to sweep the model’s output into a tidy data frame. This will prevent entry errors and promote exact calculations.</p>
<pre class="r"><code>(maglio_tidy &lt;- tidy(maglio_anova))</code></pre>
<pre><code>## # A tibble: 5 x 5
##   term                sumsq    df statistic   p.value
##   &lt;chr&gt;               &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
## 1 (Intercept)         347.      1     324.   3.34e-43
## 2 orientation          13.1     1      12.2  5.89e- 4
## 3 station              51.2     3      15.9  2.76e- 9
## 4 orientation:station  52.4     3      16.3  1.77e- 9
## 5 Residuals           208.    194      NA   NA</code></pre>
<p>Now, calculating the effect size is a simple plug-in procedure.</p>
<pre class="r"><code>(eta_station &lt;- maglio_tidy$sumsq[3] / (maglio_tidy$sumsq[3] + maglio_tidy$sumsq[5]))</code></pre>
<pre><code>## [1] 0.1973795</code></pre>
<pre class="r"><code>(eta_interact &lt;- maglio_tidy$sumsq[4] / (maglio_tidy$sumsq[4] + maglio_tidy$sumsq[5]))</code></pre>
<pre><code>## [1] 0.2011516</code></pre>
<p>The two-way ANOVA revealed no main effect on orientaion, <em>F</em> &lt; 1, <em>p</em> = .573. The <em>F</em>-value did not exceed the critical value. However, there was a significant effect on station, <em>F</em>(3, 194) = 24.10, <em>p</em> &lt; .001, <span class="math inline">\(\eta_p^2 = .27\)</span>. The interaction between orientation and station was also significant, <em>F</em>(3, 194) = 16.28, <em>p</em> &lt; .001, <span class="math inline">\(\eta_p^2 = .20\)</span>.</p>
<div id="outliers" class="section level4">
<h4>Outliers?</h4>
<p>Outliers can reduce the accuracy of results and skew data.</p>
<pre class="r"><code>ggplot(maglio_clean, aes(x = station, y = subjective_distance, color = orientation)) +
  geom_boxplot()</code></pre>
<p><img src="/post/osl-maglio-polman-2014_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>There are three outliers present.</p>
</div>
<div id="normality" class="section level4">
<h4>Normality?</h4>
<p>The null hypothesis of the Shapiro-Wilk test is that the data are normally distributed. Remember that, for analysis of variance, we test the normality of residuals.</p>
<pre class="r"><code>aov_residuals &lt;- residuals(maglio_aov)
shapiro.test(aov_residuals)</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  aov_residuals
## W = 0.97245, p-value = 0.0005304</code></pre>
<p>Since <em>p</em> &lt; .001, we reject the null hypothesis: the data are not normally distributed. The ANOVA is a robust procedure, so it can withstand violations of normality. Let’s visualize the distribution.</p>
<p>One method is the Q-Q plot, a visualization that compares the quantiles of a normal distribution against the quantiles of the model’s residuals. Normally distributed residuals will follow a straight diagonal line.</p>
<pre class="r"><code>plot(maglio_aov, 2)</code></pre>
<p><img src="/post/osl-maglio-polman-2014_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p>Here, we see that the residuals undulate along the line. The pattern seems consistent if not normal, despite the labeled outliers in the upper right-hand corner of the plot.</p>
<p>What does a density curve for each cell (i.e., group) reveal?</p>
<pre class="r"><code>ggplot(maglio_clean, aes(x = subjective_distance)) +
  geom_density() +
  facet_grid(orientation ~ station)</code></pre>
<p><img src="/post/osl-maglio-polman-2014_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>The data are clearly not normal. They are not even skewed in similar directions!</p>
</div>
<div id="homoscedasticity" class="section level4">
<h4>Homoscedasticity?</h4>
<p>The null hypothesis of Levene’s test is that the variances are homogeneous.</p>
<pre class="r"><code>leveneTest(subjective_distance ~ orientation * station, data = maglio_clean)</code></pre>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = median)
##        Df F value Pr(&gt;F)
## group   7  0.5781 0.7732
##       194</code></pre>
<p>There is no evidence in favor of rejecting the null hypothesis, <em>F</em> &lt; 1, <em>p</em> = .773. The data are homoscedastic.</p>
<p>We can also visualize homogenity of variances as the relationship between residuals and fitted values.</p>
<pre class="r"><code>plot(maglio_aov, 1)</code></pre>
<p><img src="/post/osl-maglio-polman-2014_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>The plot shows no relationship. The red line is practically at zero.</p>
</div>
</div>
<div id="independent-t-tests" class="section level3">
<h3>Independent t-Tests</h3>
<p>The assumptions of the independent t-test are nearly identical to the two-way ANOVA, except for the requirement of the independent variable, which in this case, must be a single factor with two or more levels. The results from the three assumptions that are tested (i.e., outliers, normality, and homoscedasticity) will likely be inherited from the ANOVA. However, we will test these assumptions below for each independent t-test.</p>
<p>We shall delineate the interaction between orientation and station by comparing the subjective-distance scores across eastbound and westbound participants for each of the stations.</p>
<p>Social scientists typically report Cohen’s <em>d</em> as the effect size of independent t-tests. Cohen’s <em>d</em> is standardized. In the present study, the author’s chose to report partial eta-squared, which indicates the <a href="http://psychology.okstate.edu/faculty/jgrice/psyc3214/independentsamples_t_test.pdf">proportion of overlap</a> between the factor and the reponse variable. Effect sizes are considered:</p>
<ul>
<li><strong>small</strong> = .01</li>
<li><strong>medium</strong> = .06</li>
<li><strong>large</strong> = .14</li>
</ul>
<p>Here’s how we calculate partial eta-squared for independent t-tests:</p>
<p><span class="math display">\[\eta_p^2 = \frac{t_{obs}^2}{t_{obs}^2 + df}\]</span></p>
<p>We will tidy the t-test model like we did above. Once the model is in a data frame, <code>statistic</code> corresponds to the observed <em>t</em>-value, whereas parameter corresponds to the degrees of freedom.</p>
<div id="spadina" class="section level4 tabset tabset-pills">
<h4>Spadina</h4>
<pre class="r"><code># Spadina t-test
(spadina_t &lt;- t.test(spadina_east$subjective_distance, spadina_west$subjective_distance,
                     paired = FALSE, var.equal = TRUE))</code></pre>
<pre><code>## 
##  Two Sample t-test
## 
## data:  spadina_east$subjective_distance and spadina_west$subjective_distance
## t = 3.4592, df = 49, p-value = 0.001131
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  0.424870 1.602822
## sample estimates:
## mean of x mean of y 
##  3.653846  2.640000</code></pre>
<pre class="r"><code># Spadina effect size
(spadina_tidy &lt;- tidy(spadina_t))</code></pre>
<pre><code>## # A tibble: 1 x 9
##   estimate1 estimate2 statistic p.value parameter conf.low conf.high method
##       &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt; 
## 1      3.65      2.64      3.46 0.00113        49    0.425      1.60 &quot; Two~
## # ... with 1 more variable: alternative &lt;chr&gt;</code></pre>
<pre class="r"><code>(eta_spadina &lt;- spadina_tidy$statistic^2 / (spadina_tidy$statistic^2 + spadina_tidy$parameter))</code></pre>
<pre><code>## [1] 0.1962763</code></pre>
<p>Westbound participants rated Spadina as being closer than eastbound participants, <em>p</em> &lt; .001, <span class="math inline">\(\eta_p^2 = .20\)</span>.</p>
<div id="outliers-1" class="section level5">
<h5>Outliers?</h5>
<pre class="r"><code>maglio_clean %&gt;% filter(station == &quot;spadina&quot;) %&gt;%
  ggplot(aes(x = direction, y = subjective_distance)) +
    geom_boxplot()</code></pre>
<p><img src="/post/osl-maglio-polman-2014_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<p>There are two outliers.</p>
</div>
<div id="normality-1" class="section level5">
<h5>Normality?</h5>
<pre class="r"><code>with(spadina_east, shapiro.test(subjective_distance))</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  subjective_distance
## W = 0.89051, p-value = 0.009669</code></pre>
<pre class="r"><code>with(spadina_west, shapiro.test(subjective_distance))</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  subjective_distance
## W = 0.88884, p-value = 0.01057</code></pre>
<p>Both <em>p</em>s &lt; .05, so we reject the null hypothesis: the data are not normal.</p>
</div>
<div id="homoscedasticity-1" class="section level5">
<h5>Homoscedasticity?</h5>
<pre class="r"><code>var.test(spadina_east$subjective_distance, spadina_west$subjective_distance)</code></pre>
<pre><code>## 
##  F test to compare two variances
## 
## data:  spadina_east$subjective_distance and spadina_west$subjective_distance
## F = 1.2075, num df = 25, denom df = 24, p-value = 0.6467
## alternative hypothesis: true ratio of variances is not equal to 1
## 95 percent confidence interval:
##  0.5348865 2.7073917
## sample estimates:
## ratio of variances 
##           1.207459</code></pre>
<p>The variances are homogeneous, <em>p</em> = .647.</p>
</div>
</div>
<div id="st.george" class="section level4 tabset tabset-pills">
<h4>St. George</h4>
<pre class="r"><code># St. George t-test
(st_george_t &lt;- t.test(st_george_east$subjective_distance, st_george_west$subjective_distance,
                      paired = FALSE, var.equal = TRUE))</code></pre>
<pre><code>## 
##  Two Sample t-test
## 
## data:  st_george_east$subjective_distance and st_george_west$subjective_distance
## t = 4.3351, df = 49, p-value = 7.229e-05
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  0.6057612 1.6527004
## sample estimates:
## mean of x mean of y 
##  2.769231  1.640000</code></pre>
<pre class="r"><code># St. George effect size
(st_george_tidy &lt;- tidy(st_george_t))</code></pre>
<pre><code>## # A tibble: 1 x 9
##   estimate1 estimate2 statistic p.value parameter conf.low conf.high method
##       &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt; 
## 1      2.77      1.64      4.34 7.23e-5        49    0.606      1.65 &quot; Two~
## # ... with 1 more variable: alternative &lt;chr&gt;</code></pre>
<pre class="r"><code>(eta_st_george &lt;- st_george_tidy$statistic^2 / 
    (st_george_tidy$statistic^2 + st_george_tidy$parameter))</code></pre>
<pre><code>## [1] 0.2772092</code></pre>
<p>Westbound participants rated St. George as being closer than eastbound participants, <em>p</em> &lt; .001, <span class="math inline">\(\eta_p^2 = .28\)</span>.</p>
<div id="outliers-2" class="section level5">
<h5>Outliers?</h5>
<pre class="r"><code>maglio_clean %&gt;% filter(station == &quot;st_george&quot;) %&gt;%
  ggplot(aes(x = direction, y = subjective_distance)) +
  geom_boxplot()</code></pre>
<p><img src="/post/osl-maglio-polman-2014_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<p>There is one outlier among eastbound participants.</p>
</div>
<div id="normality-2" class="section level5">
<h5>Normality?</h5>
<pre class="r"><code>with(st_george_east, shapiro.test(subjective_distance))</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  subjective_distance
## W = 0.88253, p-value = 0.006513</code></pre>
<pre class="r"><code>with(st_george_west, shapiro.test(subjective_distance))</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  subjective_distance
## W = 0.72533, p-value = 1.629e-05</code></pre>
<p>Since both <em>p</em>s &lt; .05, we accept the alternative hypothesis: the data are not normally distributed.</p>
</div>
<div id="homoscedasticity-2" class="section level5">
<h5>Homoscedasticity?</h5>
<pre class="r"><code>var.test(st_george_east$subjective_distance, st_george_west$subjective_distance)</code></pre>
<pre><code>## 
##  F test to compare two variances
## 
## data:  st_george_east$subjective_distance and st_george_west$subjective_distance
## F = 1.6212, num df = 25, denom df = 24, p-value = 0.2407
## alternative hypothesis: true ratio of variances is not equal to 1
## 95 percent confidence interval:
##  0.718186 3.635184
## sample estimates:
## ratio of variances 
##           1.621242</code></pre>
<p>Since <em>p</em> = .241, we accept the null hypothesis: the data are homoscedastic.</p>
</div>
</div>
<div id="bloor-yonge" class="section level4 tabset tabset-pills">
<h4>Bloor-Yonge</h4>
<pre class="r"><code># Bloor-Yonge t-test
(bloor_yonge_t &lt;- t.test(bloor_yonge_west$subjective_distance,
                         bloor_yonge_east$subjective_distance,
                         paired = FALSE, var.equal = TRUE))</code></pre>
<pre><code>## 
##  Two Sample t-test
## 
## data:  bloor_yonge_west$subjective_distance and bloor_yonge_east$subjective_distance
## t = 1.9863, df = 47, p-value = 0.05285
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -0.00746818  1.17469226
## sample estimates:
## mean of x mean of y 
##  2.192308  1.608696</code></pre>
<pre class="r"><code># Bloor-Yonge effect size
(bloor_yonge_tidy &lt;- tidy(bloor_yonge_t))</code></pre>
<pre><code>## # A tibble: 1 x 9
##   estimate1 estimate2 statistic p.value parameter conf.low conf.high method
##       &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt; 
## 1      2.19      1.61      1.99  0.0528        47 -0.00747      1.17 &quot; Two~
## # ... with 1 more variable: alternative &lt;chr&gt;</code></pre>
<pre class="r"><code>(eta_bloor_yonge &lt;- bloor_yonge_tidy$statistic^2 /
    (bloor_yonge_tidy$statistic^2 + bloor_yonge_tidy$parameter))</code></pre>
<pre><code>## [1] 0.0774451</code></pre>
<p>Eastbound participants rated Bloor-Yonge as being closer than westbound participants, <em>p</em> = .053, <span class="math inline">\(\eta_p^2 = .08\)</span>.</p>
<div id="outliers-3" class="section level5">
<h5>Outliers?</h5>
<pre class="r"><code>maglio_clean %&gt;% filter(station == &quot;bloor_yonge&quot;) %&gt;%
  ggplot(aes(x = direction, y = subjective_distance)) +
  geom_boxplot()</code></pre>
<p><img src="/post/osl-maglio-polman-2014_files/figure-html/unnamed-chunk-25-1.png" width="672" /></p>
<p>No outliers present.</p>
</div>
<div id="normality-3" class="section level5">
<h5>Normality?</h5>
<pre class="r"><code>with(bloor_yonge_west, shapiro.test(subjective_distance))</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  subjective_distance
## W = 0.83665, p-value = 0.0007924</code></pre>
<pre class="r"><code>with(bloor_yonge_east, shapiro.test(subjective_distance))</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  subjective_distance
## W = 0.75276, p-value = 7.355e-05</code></pre>
<p>Both <em>p</em>s &lt; .05, so we reject the null hypothesis. The normality assumption is violated.</p>
</div>
<div id="homoscedasticity-3" class="section level5">
<h5>Homoscedasticity?</h5>
<pre class="r"><code>var.test(bloor_yonge_west$subjective_distance, bloor_yonge_east$subjective_distance)</code></pre>
<pre><code>## 
##  F test to compare two variances
## 
## data:  bloor_yonge_west$subjective_distance and bloor_yonge_east$subjective_distance
## F = 2.9163, num df = 25, denom df = 22, p-value = 0.01352
## alternative hypothesis: true ratio of variances is not equal to 1
## 95 percent confidence interval:
##  1.257153 6.616943
## sample estimates:
## ratio of variances 
##           2.916282</code></pre>
<p>Since <em>p</em> &lt; .05, we reject the null hypothesis: the variances are heterogeneous.</p>
</div>
</div>
<div id="sherbourne" class="section level4 tabset tabset-pills">
<h4>Sherbourne</h4>
<pre class="r"><code># Sherbourne t-test
(sherbourne_t &lt;- t.test(sherbourne_west$subjective_distance, sherbourne_east$subjective_distance,
                        paired = FALSE, var.equal = TRUE))</code></pre>
<pre><code>## 
##  Two Sample t-test
## 
## data:  sherbourne_west$subjective_distance and sherbourne_east$subjective_distance
## t = 3.8869, df = 49, p-value = 0.0003052
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  0.5944498 1.8670886
## sample estimates:
## mean of x mean of y 
##  4.000000  2.769231</code></pre>
<pre class="r"><code># Sherbourne effect size
(sherbourne_tidy &lt;- tidy(sherbourne_t))</code></pre>
<pre><code>## # A tibble: 1 x 9
##   estimate1 estimate2 statistic p.value parameter conf.low conf.high method
##       &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt; 
## 1         4      2.77      3.89 3.05e-4        49    0.594      1.87 &quot; Two~
## # ... with 1 more variable: alternative &lt;chr&gt;</code></pre>
<pre class="r"><code>(eta_sherbourne &lt;- sherbourne_tidy$statistic^2 / 
    (sherbourne_tidy$statistic^2 + sherbourne_tidy$parameter))</code></pre>
<pre><code>## [1] 0.2356667</code></pre>
<p>Eastbound participants rated Sherbourne as being closer than westbound participants, <em>p</em> &lt; .001, <span class="math inline">\(\eta_p^2 = .24\)</span>.</p>
<div id="outliers-4" class="section level5">
<h5>Outliers?</h5>
<pre class="r"><code>maglio_clean %&gt;% filter(station == &quot;sherbourne&quot;) %&gt;%
  ggplot(aes(x = direction, y = subjective_distance)) +
  geom_boxplot()</code></pre>
<p><img src="/post/osl-maglio-polman-2014_files/figure-html/unnamed-chunk-29-1.png" width="672" /></p>
<p>No outliers.</p>
</div>
<div id="normality-4" class="section level5">
<h5>Normality?</h5>
<pre class="r"><code>with(sherbourne_west, shapiro.test(subjective_distance))</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  subjective_distance
## W = 0.89339, p-value = 0.01321</code></pre>
<pre class="r"><code>with(sherbourne_east, shapiro.test(subjective_distance))</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  subjective_distance
## W = 0.90999, p-value = 0.02635</code></pre>
<p>The data are not normally distributed (both <em>p</em>s &lt; .05).</p>
</div>
<div id="homoscedasticity-4" class="section level5">
<h5>Homoscedasticity?</h5>
<pre class="r"><code>var.test(sherbourne_west$subjective_distance, sherbourne_east$subjective_distance)</code></pre>
<pre><code>## 
##  F test to compare two variances
## 
## data:  sherbourne_west$subjective_distance and sherbourne_east$subjective_distance
## F = 0.95814, num df = 24, denom df = 25, p-value = 0.9188
## alternative hypothesis: true ratio of variances is not equal to 1
## 95 percent confidence interval:
##  0.4273157 2.1629094
## sample estimates:
## ratio of variances 
##          0.9581368</code></pre>
<p>The variances are equal (<em>p</em> = .919).</p>
</div>
</div>
</div>
<div id="visualize" class="section level3">
<h3>Visualize</h3>
<p>Let’s generate a line graph to depict the relationship between station and the direction of travel, which corresponds to orientation.</p>
<p>First we need to construct an APA-style theme.</p>
<pre class="r"><code>apa_theme &lt;- theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        axis.line = element_line(),
        plot.title = element_text(hjust = 0.5),
        text = element_text(size = 12))</code></pre>
<p>Next, we need the mean and standard error of subjective-distance ratings for westbound and eastbound participants for each station. The following code is clunky, but it accomplishes the task.</p>
<pre class="r"><code>sp_e &lt;- describe(spadina_east$subjective_distance)[,-c(1:2,4:12)]
sp_w &lt;- describe(spadina_west$subjective_distance)[,-c(1:2,4:12)]
st_e &lt;- describe(st_george_east$subjective_distance)[,-c(1:2,4:12)]
st_w &lt;- describe(st_george_west$subjective_distance)[,-c(1:2,4:12)]
bl_e &lt;- describe(bloor_yonge_east$subjective_distance)[,-c(1:2,4:12)]
bl_w &lt;- describe(bloor_yonge_west$subjective_distance)[,-c(1:2,4:12)]
sh_e &lt;- describe(sherbourne_east$subjective_distance)[,-c(1:2,4:12)]
sh_w &lt;- describe(sherbourne_west$subjective_distance)[,-c(1:2,4:12)]</code></pre>
<p>Bind the temporary variables holding the descriptive statistics into one variable, adding two new columns for direction and station.</p>
<pre class="r"><code>descriptives &lt;- rbind(sp_e, sp_w, st_e, st_w, bl_e, bl_w, sh_e, sh_w)

# Add columns
(descriptives &lt;- descriptives %&gt;%
  mutate(
    direction = c(&quot;east&quot;, &quot;west&quot;, &quot;east&quot;, &quot;west&quot;, &quot;east&quot;, &quot;west&quot;, &quot;east&quot;, &quot;west&quot;),
    station = c(&quot;spadina&quot;, &quot;spadina&quot;, &quot;st_george&quot;, &quot;st_george&quot;, 
                &quot;bloor_yonge&quot;, &quot;bloor_yonge&quot;, &quot;sherbourne&quot;, &quot;sherbourne&quot;)
  ))</code></pre>
<pre><code>##       mean        se direction     station
## 1 3.653846 0.2144209      east     spadina
## 2 2.640000 0.1989975      west     spadina
## 3 2.769231 0.2023530      east   st_george
## 4 1.640000 0.1620699      west   st_george
## 5 1.608696 0.1506131      east bloor_yonge
## 6 2.192308 0.2419105      west bloor_yonge
## 7 2.769231 0.2240034      east  sherbourne
## 8 4.000000 0.2236068      west  sherbourne</code></pre>
<p>Transform the variables station and direction into factors with pretty labels.</p>
<pre class="r"><code># Station
descriptives$station &lt;- factor(descriptives$station, 
                               levels = c(&quot;spadina&quot;, &quot;st_george&quot;, &quot;bloor_yonge&quot;, &quot;sherbourne&quot;),
                               labels = c(&quot;Spadina&quot;, &quot;St. George&quot;, &quot;Bloor-Yonge&quot;, &quot;Sherbourne&quot;))

# Direction
descriptives$direction &lt;- factor(descriptives$direction,
                                 levels = c(&quot;east&quot;, &quot;west&quot;),
                                 labels = c(&quot;Eastbound&quot;, &quot;Westbound&quot;))</code></pre>
<p>Finally, we construct the line graph to <a href="https://drsimonj.svbtle.com/mean-and-ci-plot-for-twoway-designs-using-ggplot2">plot this two-way design</a>.</p>
<pre class="r"><code>ggplot(descriptives, aes(x = station, y = mean, group = direction)) +
  geom_line(aes(linetype = direction), size = 1) +
  geom_errorbar(aes(ymin = mean - se, ymax = mean + se), width = 0.1) +
  geom_point(size = 5, position = position_dodge(width = 0.01)) +
  geom_point(size = 4, position = position_dodge(width = 0.01), color = &quot;white&quot;) +
  expand_limits(y = c(0, 5)) +
  scale_y_continuous(breaks = seq(0, 5, 0.5), expand = c(0, 0)) +
  guides(linetype = guide_legend(&quot;&quot;)) +
  labs(x = &quot;&quot;, y = &quot;Subjective Distance&quot;) +
  apa_theme +
  theme(legend.position = c(0.1, 0.99))</code></pre>
<p><img src="/post/osl-maglio-polman-2014_files/figure-html/unnamed-chunk-36-1.png" width="672" /></p>
<p><strong>Figure 1</strong>: The mean subjective-distance rating for each group based on their orientation towards and away from the four stations.</p>
</div>
</div>
<div id="communicate" class="section level2">
<h2>Communicate</h2>
<hr />
<p>The two-way ANOVA revealed no main effect on orientaion, <em>F</em> &lt; 1, <em>p</em> = .573. The <em>F</em>-value did not exceed the critical value. However, there was a significant effect on station, <em>F</em>(3, 194) = 24.10, <em>p</em> &lt; .001, <span class="math inline">\(\eta_p^2 = .27\)</span>. The interaction between orientation and station was also significant, <em>F</em>(3, 194) = 16.28, <em>p</em> &lt; .001, <span class="math inline">\(\eta_p^2 = .20\)</span>. Delineation of this interaction revealed that eastbound participants perceived stations to the East as being closer than did westbound participants, both for Bloor-Yonge (<em>p</em> = .053, <span class="math inline">\(\eta_p^2 = .08\)</span>) and Sherbourne (<em>p</em> &lt; .001, <span class="math inline">\(\eta_p^2 = .24\)</span>). Travlers heading west from Bay station rated the subjective-distance of St. George (<em>p</em> &lt; .001, <span class="math inline">\(\eta_p^2 = .28\)</span>) and Spadina (<em>p</em> &lt; .001, <span class="math inline">\(\eta_p^2 = .20\)</span>) as closer than did eastbound participants.</p>
</div>
</div>
<div id="acknowledgements" class="section level1">
<h1>Acknowledgements</h1>
<hr />
<p>I am thankful for my advisor, Dr. Brandt A. Smith for introducing me to R, JASP, and OSL. The discipline of psychology is advocating for preregistered, open materials. His encouragement to utilize open data and open source software has positioned me in the middle of the reproducible movement.</p>
<p>I would still be clicking checkboxes and dropdowns to analyze data if it were not for <a href="https://www.datacamp.com">DataCamp</a>, <a href="https://rstudio-pubs-static.s3.amazonaws.com/65059_586f394d8eb84f84b1baaf56ffb6b47f.html">Rose Maier</a>, <a href="http://www.sthda.com/english/wiki/two-way-anova-test-in-r">Alboukadel Kassambara</a>, <a href="https://www.sas.upenn.edu/~baron/from_cattell/rpsych/rpsych.html#htoc60">Jonathan Baron</a>, and the team behind <a href="http://personality-project.org/r/r.guide.html#withinone">personality-project</a>.</p>
</div>
